[package]
name = "rchtmltopdf-browser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "rchtmltopdf browser layer"

[dependencies]
rchtmltopdf-core.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt", "io-util", "sync", "time", "macros"] }
